/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AbstractObjekat;
import domen.RezervacijaVoznje;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.ModelPrikazRezervacija;

/**
 *
 * @author Daniel
 */
public class FmRezervacijePrikaz extends javax.swing.JFrame {

    private List<AbstractObjekat> listaRezervacija;
    JFrame parent;

    public void setParent(JFrame parent) {
        this.parent = parent;
    }

    /**
     * Creates new form FmRezervacijePrikaz
     */
    public FmRezervacijePrikaz() {
        initComponents();
        srediFormu();
        setLocationRelativeTo(null);
        setTitle("Prikaz rezervacija");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rezervacije = new javax.swing.JTable();
        btn_izmeni = new javax.swing.JButton();
        txt_pretraga = new javax.swing.JTextField();
        btn_pretrazi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbl_rezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_rezervacije);

        btn_izmeni.setText("Izmeni");
        btn_izmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izmeniActionPerformed(evt);
            }
        });

        txt_pretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pretragaKeyReleased(evt);
            }
        });

        btn_pretrazi.setText("Pretrazi");
        btn_pretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pretraziActionPerformed(evt);
            }
        });

        jButton1.setText("Obrisi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txt_pretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pretrazi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_izmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_izmeni)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_izmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izmeniActionPerformed
        // TODO add your handling code here:
        if (tbl_rezervacije.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(parent, "Odaberite rezervaciju!");
        } else {
            RezervacijaVoznje rez = (RezervacijaVoznje) listaRezervacija.get(tbl_rezervacije.getSelectedRow());
            FmRezervacija fmr = new FmRezervacija(rez);
            fmr.setParent(this);
            this.setVisible(false);
            fmr.setVisible(true);
        }
    }//GEN-LAST:event_btn_izmeniActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_pretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pretraziActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String pretraga = txt_pretraga.getText();
            if (pretraga.isEmpty()) {
                listaRezervacija = Kontroler.vratiInstancuKontrolera().ucitajListuRezervacija();
            } else {
                listaRezervacija = Kontroler.vratiInstancuKontrolera().pretraziRezervacije(pretraga);
            }
            ModelPrikazRezervacija mpr = (ModelPrikazRezervacija) tbl_rezervacije.getModel();
            mpr.setListaRezervacija(listaRezervacija);
            mpr.fireTableDataChanged();
            if (listaRezervacija.size() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje rezervaciju!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_pretraziActionPerformed

    private void txt_pretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pretragaKeyReleased

    }//GEN-LAST:event_txt_pretragaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tbl_rezervacije.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(parent, "Odaberite rezervaciju!");
        } else {

            try {
                RezervacijaVoznje rez = (RezervacijaVoznje) listaRezervacija.get(tbl_rezervacije.getSelectedRow());
                List<AbstractObjekat> listaPosleBris = Kontroler.vratiInstancuKontrolera().obrisiRezervacij(rez);
                ModelPrikazRezervacija mpr = (ModelPrikazRezervacija) tbl_rezervacije.getModel();
                mpr.setListaRezervacija(listaPosleBris);
                mpr.fireTableDataChanged();
                JOptionPane.showMessageDialog(rootPane, "Sistem je uspesno obrisao rezervaciju", "Brisanje rezervacije", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Sistem ne moze da obrise rezervaciju!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmRezervacijePrikaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_izmeni;
    private javax.swing.JButton btn_pretrazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_rezervacije;
    private javax.swing.JTextField txt_pretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            listaRezervacija = Kontroler.vratiInstancuKontrolera().ucitajListuRezervacija();
            ModelPrikazRezervacija mpr = new ModelPrikazRezervacija(listaRezervacija);
            tbl_rezervacije.setModel(mpr);
        } catch (Exception ex) {
            Logger.getLogger(FmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
