/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AbstractObjekat;
import domen.MotorneSanke;
import domen.RezervacijaVoznje;
import domen.StavkaRezervacijeVoznje;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.ModelPrikazSanke;
import sesija.Sesija;

/**
 *
 * @author Daniel
 */
public class FmSankePrikaz extends javax.swing.JFrame {

    private FmGlavna parent;

    public FmGlavna getParent() {
        return parent;
    }

    public void setParent(FmGlavna parent) {
        this.parent = parent;
    }
    /**
     * Creates new form FmSankePrikaz
     */
    public FmSankePrikaz() {
        initComponents();
//        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanke = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_izmeni = new javax.swing.JButton();
        txt_pretrazi = new javax.swing.JTextField();
        btn_pretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl_sanke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_sanke);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_izmeni.setText("Izmeni");
        btn_izmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izmeniActionPerformed(evt);
            }
        });

        btn_pretrazi.setText("Pretrazi");
        btn_pretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_izmeni)
                        .addGap(121, 121, 121)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txt_pretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_pretrazi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_pretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_izmeni))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        srediFormu();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            List<AbstractObjekat> listaRezervacija = Kontroler.vratiInstancuKontrolera().ucitajListuRezervacija();
            for (AbstractObjekat abstractObjekat : listaRezervacija) {
                RezervacijaVoznje rv = (RezervacijaVoznje) abstractObjekat;
                System.out.println(rv);
                for (AbstractObjekat abstractObjekat1 : rv.getListaStavki()) {
                    StavkaRezervacijeVoznje srv = (StavkaRezervacijeVoznje) abstractObjekat1;
                    System.out.println(srv);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FmSankePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_izmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izmeniActionPerformed
        ModelPrikazSanke mps = (ModelPrikazSanke) tbl_sanke.getModel();
        MotorneSanke selected = (MotorneSanke) mps.getListaSanki().get(tbl_sanke.getSelectedRow());
        FmMotorneSanke izmena = new FmMotorneSanke(selected, this);
        izmena.setVisible(true);
    }//GEN-LAST:event_btn_izmeniActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void btn_pretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pretraziActionPerformed
        // TODO add your handling code here:
        String pretraga = txt_pretrazi.getText();
        List<AbstractObjekat> lista;
        try {
            if (pretraga.isEmpty()) {
                lista = Kontroler.vratiInstancuKontrolera().ucitajListuMotornihSanki();
            } else {
                lista = Kontroler.vratiInstancuKontrolera().pretraziSanke(pretraga);
            }
            ModelPrikazSanke mps = (ModelPrikazSanke) tbl_sanke.getModel();
            mps.setListaSanki(lista);
            mps.fireTableDataChanged();
        } catch (Exception ex) {
            Logger.getLogger(FmSankePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_pretraziActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmSankePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmSankePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmSankePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmSankePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmSankePrikaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_izmeni;
    private javax.swing.JButton btn_pretrazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sanke;
    private javax.swing.JTextField txt_pretrazi;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        List<AbstractObjekat> lista;
        try {
            lista = Kontroler.vratiInstancuKontrolera().ucitajListuMotornihSanki();
            tbl_sanke.setModel(new ModelPrikazSanke(lista));
            Sesija.vratiInstancu().getMapa().put("listaSanki", lista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }
}
